# Generated by Django 3.2.7 on 2021-10-07 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialdeCompras',
            fields=[
                ('Id_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.FloatField()),
                ('Estado', models.CharField(max_length=50)),
                ('FechadeCompra', models.DateField(blank=True)),
                ('Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
